/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package b.currencycrawler;

import b.currencycrawler.verticles.CurrencyGeneratorVerticle;
import com.mybaas.AppRunner;

import java.util.Calendar;

public class App {


    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        try {
            new AppRunner().setVerticleToRun(CurrencyGeneratorVerticle.class).Dispatch(args);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
