
/*
* This Java source file was generated by the Gradle 'init' task.
 */
package vertx.breadboard;

public class App {
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public String getGreeting() {
        return "Hello world.";
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
