/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package b.breadboard;

import b.breadboard.diworks.guice.DITestingApp;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;


public class App {
    private static Logger logger = LogManager.getLogger(App.class);
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        logger.info("This is from log4j2");
        System.out.println(new App().getGreeting());
        new DITestingApp().run();
        logger.info("This is from log4j2 END");
    }
}
