/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package b.contentcollector;

import b.contentcollector.verticles.ContentDownloaderVerticle;
import com.mybaas.AppRunner;
import com.mybaas.utils.ConsoleUtils;
import com.mybaas.utils.ResourceUtils;
import org.slf4j.LoggerFactory;

import java.io.IOException;

public class App {

    public static void main(String[] args) {
        try {
            AppRunner.initInstance()
                        .setVerticleToRun(ContentDownloaderVerticle.class)
                        .Dispatch(args);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


}
