/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package b;

import b.contentanalyzer.verticles.ContentParserAndAnalyzerVerticle;
import b.contentdownloader.verticles.ContentDownloadServiceVerticle;
import b.contentdownloader.verticles.ContentDownloadVerticle;
import b.contentdownloader.verticles.ContentDownloaderRestApiVerticle;
import b.downloadclock.verticles.DownloadRequestEmitterVerticle;
import com.mybaas.AppRunner;

public class App {

    public static void main(String[] args) {
        try {
            AppRunner.initInstance()
                        .setVerticlesToRun(ContentDownloadServiceVerticle.class,
                                           ContentDownloadVerticle.class,
                                           DownloadRequestEmitterVerticle.class,
                                            ContentDownloaderRestApiVerticle.class,
                                            ContentParserAndAnalyzerVerticle.class)
                        .Dispatch(args);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


}
