/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.mybaas.utils;
import java.util.UUID;


public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static String getUniqeuID () {
        UUID id = UUID.randomUUID();
        return id.toString();
    }
}
